name: Build APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk unzip git zip build-essential libffi-dev libssl-dev libjpeg-dev zlib1g-dev ffmpeg
        pip3 install --upgrade pip
        pip3 install Cython==0.29.33 buildozer cython  # pin Cython per known issues

    - name: Build APK
      run: |
        buildozer android clean  # ensure a clean build
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: jarvis-apk
        path: bin/*.apk
